from math import *
a=float(input())
b=float(input())
c=float(input())
aa=degrees(acos((b**2+c**2-a**2)/(2*b*c)))
ab=degrees(acos((a**2+c**2-b**2)/(2*a*c)))
ac=degrees(acos((b**2+a**2-c**2)/(2*b*a)))
print(aa)
print(ab)
print(ac)